# Generated by Django 5.1.6 on 2025-04-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='membership_type',
            field=models.CharField(default='Individual Membership', max_length=50),
        ),
        migrations.AlterField(
            model_name='register',
            name='membership_type',
            field=models.CharField(default='Individual Membership', max_length=50),
        ),
    ]
