# Generated by Django 5.1.6 on 2025-02-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_delete_todoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=50)),
                ('Lastname', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('Dateofbirth', models.DateField()),
                ('Gender', models.CharField(max_length=50)),
                ('MobileNumber', models.IntegerField()),
                ('Address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('Interests', models.CharField(max_length=50)),
            ],
        ),
    ]
