# Generated by Django 5.1.6 on 2025-04-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_membership_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipupgraderequest',
            name='requested_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.membership'),
        ),
    ]
