# Generated by Django 5.1.6 on 2025-04-02 00:39

import django.db.models.deletion
from django.db import migrations, models

def populate_membership_type(apps, schema_editor):
    Membership = apps.get_model('myapp', 'Membership')
    CustomUser = apps.get_model('myapp', 'CustomUser')

    # Create a mapping of existing Membership names to their instances
    memberships = {m.name: m for m in Membership.objects.all()}

    # Create missing Membership instances for any string values in membership_type
    for user in CustomUser.objects.all():
        if user.membership_type_temp and user.membership_type_temp not in memberships:
            memberships[user.membership_type_temp] = Membership.objects.create(name=user.membership_type_temp)

    # Migrate data from the temporary field to the new ForeignKey field
    for user in CustomUser.objects.all():
        if user.membership_type_temp in memberships:
            user.membership_type = memberships[user.membership_type_temp]
            user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_membershipupgraderequest_requested_type'),
    ]

    operations = [
        # Add a temporary field to store the old string values
        migrations.AddField(
            model_name='customuser',
            name='membership_type_temp',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        # Populate the temporary field with the old data
        migrations.RunPython(
            code=lambda apps, schema_editor: apps.get_model('myapp', 'CustomUser').objects.update(
                membership_type_temp=models.F('membership_type')
            ),
            reverse_code=migrations.RunPython.noop,
        ),
        # Change the membership_type field to a ForeignKey
        migrations.AlterField(
            model_name='customuser',
            name='membership_type',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='myapp.membership',
            ),
        ),
        # Populate the new ForeignKey field using the temporary field
        migrations.RunPython(populate_membership_type, reverse_code=migrations.RunPython.noop),
        # Remove the temporary field
        migrations.RemoveField(
            model_name='customuser',
            name='membership_type_temp',
        ),
    ]
