# Generated by Django 5.1.6 on 2025-02-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='Member',
        ),
    ]
