# Generated by Django 5.1.6 on 2025-04-02 01:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_customuser_membership_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='joined_users',
            field=models.ManyToManyField(blank=True, related_name='joined_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
