# Generated by Django 5.1.6 on 2025-03-25 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('Workshops', 'Workshops'), ('Meetups', 'Meetups'), ('Creative Sessions', 'Creative Sessions')], max_length=100),
        ),
    ]
