# Generated by Django 5.1.6 on 2025-03-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_address_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('Individual Membership', 'Individual Membership'), ('Community Membership', 'Community Membership'), ('Workspace Membership', 'Workspace Membership'), ('Organisational Membership', 'Organisational Membership')], default='Individual Membership', max_length=50),
        ),
    ]
